spring.application.name=springBoot
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=ferPostSQL

#Creación de las tablas de base de datos

spring.jpa.hibernate.ddl-auto=update

#Muestra las consultas estructuradas en la terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
